# OSEMN Exercises

In [3]:
%matplotlib inline
import pandas as pd
import numpy as np
from numpy import random

1\. Create a random list of number and then save it to a text file named "simple_data.txt"

In [10]:
d = random.random(size=100)
print(d)

filename = "simple_data.txt"

with open(filename, mode = 'w') as f:
    for point in d:
        f.write(str(point) + '\n')

[5.38826776e-01 7.57965361e-01 9.11585491e-01 8.23464793e-01
 5.49727940e-02 7.45906383e-01 9.05486815e-01 6.43773233e-01
 4.64457921e-01 9.03453776e-01 7.48525943e-03 8.40106960e-01
 2.13270255e-01 9.35060282e-01 2.48423298e-01 6.28358746e-01
 3.32615383e-01 8.36521198e-01 4.89520965e-01 4.87449855e-01
 1.33854053e-01 6.60687725e-01 6.09101973e-01 4.92902500e-01
 6.94090133e-01 6.96873387e-01 1.15892070e-01 8.27270289e-01
 2.95775812e-01 6.94123145e-01 4.53355510e-01 5.02043836e-01
 9.59796649e-02 6.85629113e-02 9.98782962e-01 3.69948080e-01
 4.84658285e-02 3.07179685e-01 8.24724714e-01 7.31699476e-01
 7.50148029e-01 3.51308968e-01 1.06416640e-01 2.73570145e-01
 8.98128053e-01 1.04881275e-01 8.47472581e-01 9.90774704e-01
 2.13748835e-01 4.86990790e-02 9.89485968e-01 4.64699084e-01
 2.60479802e-01 4.98362944e-02 6.70383167e-01 8.33055445e-01
 4.78077384e-01 9.71720319e-01 9.35540217e-01 3.43293326e-01
 3.03999538e-01 6.18208941e-01 4.28960789e-01 2.69327157e-02
 3.39890292e-01 1.906928

2\. Create a random matrix of 5x5 and then save it to a text file named "data.txt"

In [17]:
matrix = np.array([[np.random.random() for _ in range(5)] for _ in range(5)])
print(matrix)

# Manual way
filename = "simple_matrix.txt"
with open(filename, mode = 'w') as f:
    for row_idx in range(matrix.shape[0]):
        for col_idx in range(matrix.shape[1]):
            f.write(str(matrix[row_idx, col_idx]) + ',')
        f.write('\n')

#Numpy automatic way
filename = "simple_matrix_numpy.txt"
np.savetxt(fname= filename, X = matrix)

[[0.1860355  0.61307529 0.05353184 0.48756715 0.38687207]
 [0.83841886 0.05152655 0.39196464 0.37101173 0.28974222]
 [0.84502642 0.5843666  0.68215965 0.60974911 0.59934688]
 [0.8320256  0.83280161 0.2834097  0.28216093 0.54109529]
 [0.38339302 0.96138523 0.00962801 0.3743062  0.97296634]]


3\. Load the saved txt file of point 2 and convert it to a csv file (by hand)

In [41]:
input_filename = "simple_matrix_numpy.txt" # here separator = ' '
matrix = np.zeros((5,5))

# Load the matrix
row_idx =0
with open(input_filename, mode = 'r') as f:
    for line in f:
        # line is a str
        # numbers is a list of str
        numbers = line.rstrip('\n').split(sep= ' ')
        matrix[row_idx, :] = numbers
        row_idx += 1
print(matrix)

# Save the matrix as .csv
filename = "simple_matrix.csv"
with open(filename, mode = 'w') as f:
    for row_idx in range(matrix.shape[0]):
        for col_idx in range(matrix.shape[1]):
            f.write(str(matrix[row_idx, col_idx]) + ',')
        f.write('\n')

#There is no built in function for .csv saving in numpy. The alternative is to use Pandas

[[0.1860355  0.61307529 0.05353184 0.48756715 0.38687207]
 [0.83841886 0.05152655 0.39196464 0.37101173 0.28974222]
 [0.84502642 0.5843666  0.68215965 0.60974911 0.59934688]
 [0.8320256  0.83280161 0.2834097  0.28216093 0.54109529]
 [0.38339302 0.96138523 0.00962801 0.3743062  0.97296634]]


4\. load the binary file named *credit_card.dat* and convert the data into the real credit-card number.
Each line correspond to a credit card number.
Each character is composed by 6 bit (even the space) and the last 4 bit are just a padding

**hint**: use the `chr()` function to convert a number to a char

5\. Load the file "user_data.json", filter the data by the "CreditCardType" field equals to "American Express". Than save the data a to CSV.

6\. Load the file from this url: [https://www.dropbox.com/s/7u3lm737ogbqsg8/mushrooms_categorized.csv?dl=1](https://www.dropbox.com/s/7u3lm737ogbqsg8/mushrooms_categorized.csv?dl=1) with Pandas. 
+ Explore the data (see the info of the data)
+ Draw the istogram of the 'class' field. Decribe wath yuou see


7\. Load the remote file [https://www.dropbox.com/s/vkl89yce7xjdq4n/regression_generated.csv?dl=1](https://www.dropbox.com/s/vkl89yce7xjdq4n/regression_generated.csv?dl=1) with Pandas and plot a scatter plot all possible combination of the following fields:
    
  + features_1
  + features_2
  + features_3

8\. Load the same file of point 6, and convert the file to json with Pandas.